---
title: "05 · Uniprocessor Scheduling"
---

## Uniprocessor Scheduling

## Types of Scheduling

- Long-term Scheduling: The decision to add to the pool of processes to be run
- Medium-term Scheduling: The decision to add to the number of processes that are partially or fully in memory
- Short-term Scheduling: The decision as to which available processes will be executed by the processor
- I/O Scheduling: The decision as to which process's pending I/O request shall be handled by an available I/O device

## The Main goal of Scheduling

- Aim to assign processes to be executed by the processor in a way that meets system objectives such as response time, throughput, and processor efficiency

## Scheduling Criteria: User Oriented

- Performance related
  - Turnaround Time: The interval of time between process creation and its completion. Includes actual execution time, plus time spent waiting for resources, including the processor. This is generally used for batch jobs.
  - Response Time: For an interactive process, this is the time from the submission of a request until the response begins to be received. Often a process can begin to produce some output to the user while continuing to process the request. Thus, this is a better measure than turnaround time from a User's point of view. This is generally for time sensitive / real-time systems such as websites
  - Deadlines: When process completion deadlines can be specified, the scheduling discipline should subordinate other goals to that of maximizing the percentage of deadlines met
- Other
  - Predictability: A given job should run in about the same amount of time and at about the same cost, regardless of the load on the system

## Scheduling Criteria: System Oriented

- Performance related:
  - Throughput: The scheudling policy should attempt to maximize the number of processes completed per unit of time. This is a measure of how much work is being performed. This clearly depends on the average amount of time a process takes, but is also influenced by the scheudling policy used.
  - Processor Utilization: This is the percentage of time that the processor is busy. For expensive shared systems, this is a significant criterion. In single user systems, and some other systems (such as real time), this criteria is less important than others

- Other:
  - Fairness: In absence of guidance from the user, or other system supplied guidance, processes should be treated the same, and no process should suffer starvation (lack of resources).
  - Priority Enforcement: When processes are assigned priorities, the scheudling policy should favor high priority processes.
  - Resource Balancing: The scheduling policy should keep the resources of the system busy. Processes that will underutilize stressed resources should be favored. This criteria mostly refers to long and medium term scheudling

## Long Term Scheduler

- Determines what programs are admitted to the system for processing
- Controls the degree of multiprogramming
  - The more processes that are created, the smaller the percentage of time that each process can be executed
  - May be limited to provide satisfactory services to the current set of processes
- Creates processes from a queue when it can, but must decide:
  - When the OS can take on one or more additional processes
  - Which jobs to accept and turn into processes
    - Can be first come, first served
    - Can be dictated by priority, expected execution time, I/O requirements

## Medium Term Scheduler

- Part of Admit and Swapping functions
- Swapping decisions are based on need for resources and to manage the degree of multiprogramming
  - Considers the resources needed of the swapped out (suspended) process

## Short Term Scheduler

- Known as the dispatcher
- Executes the most frequently
- Makes the fine-grained decision of which process to execute next
- Invoked when an even occurs that may lead to the blocking of the current process, or that may provide an opportunity to preempt a currently running process in favor of another
  - Examples:
    - clock interrupts
    - I/O interrupts
    - OS system calls
    - Signals (i.e. Semaphores (discussed later))

## Short Term Scheduler Criteria

- Performance:
  - Quantitative
  - Easily measured
  - Throughput/Response time

## Process Behavior

- Processes alternate bursts of computing with I/O requests
  - Some processes spend most of their time computing: CPU bound
  - Some processes spend most of their time waiting for I/O: I/O bound
- There are generally more small-medium cpu bursts than long

## CPU Scheduler

- The CPU scheduler selects from among processes in the ready queue and allocates a CPU core (uniprocessor) to one of them
  - Queue can be ordered by burst time, priority, execution time, etc.
- CPU Scheduler can make 4 choices based on process states:
  1. Switch from running to waiting
  2. Switch from running to ready
  3. Switch from waiting to ready
  4. Terminate the process

## Selection Function

- Determines which process, among ready processes, is selected for next execution
- May be based on priority, resource management, or execution charactaristcs of the process
  - If based on charactaristcs, the important quanitites are:
    - w: Time spent waiting in the system
    - e: Time spent in execution
    - s: Total serivce time required by the process, including e: generally this quantity must be estimated or supplied by the user

## Preemptive Scheduling and Nonpreemptive Scheduling

- Nonpreemptive scheduling: Once the CPU has been allocated to a process, the process keeps the CPU until it either releases by switching to waiting, or is terminated
- Anything else is preemptive
- Virtually all modern OS (like windows, mac, etc) use preemptive scheduling

## Preemptive Scheduling and Race conditions

- Preemptive scheduling can result in race conditions when data is shared between several processes
- Consider a case where two processes share the same data. While one process is updating the data, it is preempted so that the second process can run. The second process then tries to read the data, but it is in an inconsistent state. ← Race condition

## Dispatcher Latency

- Dispatcher latency: The time it takes for the dispatcher to stop one process from running and start running another process

## Scheduling Algorithm Goals: To be filled in later

## Scheduling Metrics

- CPU Utilization
- Throughput
- Turnaround time
- Waiting time: amount of time a process waits before executing
- Response time

## Scheduling Algorithms

- First-Come, First-Served (FCFS):
  - The simplest CPU-Scheduling Algorithm
  - Processes are assigned to the CPU in the order they arrive in the ready queue
  - Nonpreemptive algorithm: Once a process is in the running state, it continues until it is blocked or terminated
  - Average W: W = (T1 + T2 + T3 + ... Tn) / n

  - Convoy effect: Short processes behind long processes have a higher average wait time

- Shortest Job First (SJF):
  - Associate each process with length of its next CPU burst
    - Use these lengths to schedule the process with the shortest time
  - SJF is optimal for nonpreemptive methods: gives minimum average waiting time for a given set of processes
  - How do we determine the length of the next CPU burst?
    - Ask the user
    - estimate
    - This is why this method is hard to implement
  - Preemptive version of the algorithm is Shortest Remaining Time First (SRTF)

- Shortest Remaining Time First (SRTF):
  - Like SJF, but if a shorter job arrives, the current job is preempted

- Round Robin (RR):
  - Preemptive
  - Each process gets a small unit of CPU time (time quantum q), usually 10-100 ms. After this time has elapsed the process is preempted and added to the end of the ready queue.
  - If there are n processes in the ready queue and the time quantum is q, then each process gets 1/n of the CPU time in chunks of at most q time units at once. No process waits more than (n-1)q time units.
  - Timer interrupts every q to dispatch next process
  - Large q: Becomes much like FCFS
  - Small q: dispatcher latency increases and decreases efficiency

- Priority Scheduling:
  - A priority number (integer) is associated with each process
  - The CPU is allocated to the process(es) with the highest priority (the smaller int is higher priority)
    - Preemptive or Nonpreemptive
  - SRTF is used if multiple processes of the same priority arrive and it is preemptive
  - SJF is used for multiple processes of the same priorirty and it is non preemptive
  - Problem: Starvation - Low priority processes may never execute
    - Solution: Aging - As time progresses, increase the priority of a process

  - Multilevel queues:
    - With priority scheduling, we have a seperate queue for each priority
    - Schedule each process from its related priority queue

  - Prioritization based on process type:
    - Highest priority: Real-time processes
    - System processes
    - Interactive processes
    - Lowest priority: Batch processes
